plugins {
    id 'java'
    id 'jdashboard.common-practice-conventions'
    id 'io.freefair.lombok' version '8.13.1'
}

group = 'com.kiwiko.jdashboard.http.client'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.github.spotbugs:spotbugs-annotations'
    implementation 'com.google.code.gson:gson'

    compileOnly 'org.projectlombok:lombok'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}