server.port=8101

# Port number must match the host port in docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5433/spring_boot_example_service_test
spring.datasource.username=jdashboard_tester
spring.datasource.password=hello